Update 60-set-shell.sh

diff --git a/run_onchange_60-set-shell.sh.tmpl b/run_onchange_60-set-shell.sh.tmpl
--- a/run_onchange_60-set-shell.sh.tmpl
+++ b/run_onchange_60-set-shell.sh.tmpl
@@ -2,5 +2,9 @@
 
 if [ $SHELL != "/bin/zsh" ]; then
     echo "execute: chsh -s /bin/zsh"
-    chsh -s /bin/zsh
+    if ! chsh -s /bin/zsh; then
+        echo "Failed to set shell with chsh -s /bin/zsh"
+        echo "Trying alternative: chsh $USER -s $(which zsh)"
+        sudo chsh $USER -s $(which zsh)
+    fi
 fi
